title: Fith Docs
email: mklopukh2019@fau.edu
description: >-
  Documentation for the Fith programming language. Fith is a stack-based
  programming language based on forth which is designed to run on the 5vm
  one-instruction-set-computer.
baseurl: "/fithlang"
url: "https://mishaklopukh.github.io"
github_username:  MishaKlopukh

remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

aux_links:
  "Source on GitHub":
    - "//github.com/MishaKlopukh/fithlang"

